In [1]:
import h5py
import numpy
from numpy import zeros

In [2]:
f = h5py.File('../data/madrigal/isr/jro20020318_drifts.001', 'r')

metadata = f['Metadata']
table = f['Data']['Table Layout']
data_parameters = metadata['Data Parameters']
experiment_notes = metadata['Experiment Notes']

column_names = [column[0].decode('utf-8') for column in data_parameters.value]
print(column_names)
data = {}
N = len(table)
# collect column names
for column_name in column_names:
    data[column_name] = zeros((N,))
# put data into table
for i, row in enumerate(table):
    for j, column_name in enumerate(column_names):
        data[column_name][i] = row[j]
f.close()

['YEAR', 'MONTH', 'DAY', 'HOUR', 'MIN', 'SEC', 'UT1_UNIX', 'UT2_UNIX', 'RECNO', 'RANGE', 'GDLATR', 'GDLONR', 'SPCST', 'PL', 'CBADN', 'INTTMS', 'AZDIR7', 'ELDIR7', 'AZDIR8', 'ELDIR8', 'GDALT', 'VIPN2', 'DVIPN2', 'VIPE1', 'DVIPE1', 'VI72', 'DVI72', 'VI82', 'DVI82', 'PAIWL', 'PACWL', 'PBIWL', 'PBCWL', 'PCIEL', 'PCCEL', 'PDIEL', 'PDCEL', '32000', '32001']


In [3]:
print(data['RECNO'])
print(data['RANGE'])

[   1.    1.    1. ...,  144.  144.  144.]
[  45.   60.   75. ...,  870.  885.  900.]


```python
f = h5py.File('../data/isr/jro20020318_drifts.001', 'r')

metadata = f['Metadata']
table = f['Data']['Table Layout']
data_parameters = metadata['Data Parameters']
experiment_notes = metadata['Experiment Notes']

column_names = [column[0].decode('utf-8') for column in data_parameters.value]
print(column_names)
data = {}
N = len(table)
# collect column names
for column_name in column_names:
    data[column_name] = zeros((N,))
# put data into table
for i, row in enumerate(table):
    for j, column_name in enumerate(column_names):
        data[column_name][i] = row[j]
f.close()
```

In [12]:
f = h5py.File('../data/madrigal/isr/jro20150722drifts_avg.001', 'r')

metadata = f['Metadata']
table = f['Data']['Table Layout']
data_parameters = metadata['Data Parameters']
experiment_notes = metadata['Experiment Notes']

column_names = [column[0].decode('utf-8') for column in data_parameters.value]
print(column_names)
data = {}
N = len(table)
# collect column names
for column_name in column_names:
    data[column_name] = zeros((N,))
# put data into table
for i, row in enumerate(table):
    for j, column_name in enumerate(column_names):
        data[column_name][i] = row[j]
f.close()

['YEAR', 'MONTH', 'DAY', 'HOUR', 'MIN', 'SEC', 'UT1_UNIX', 'UT2_UNIX', 'RECNO', 'GDLATR', 'GDLONR', 'SPCST', 'PL', 'CBADN', 'INTTMS', 'RANGE', 'GDALT', 'ALTAV', 'VIPN2', 'DVIPN2', 'VIPE1', 'DVIPE1']


In [16]:
ranges = data['RANGE']
recnos = data['RECNO']

In [30]:
for i in range(int(numpy.max(recnos))):
    print(ranges[recnos == i], data['ALTAV'][recnos == i])

[] []
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  488.  548.  398.] [  60.   60.   60.   60.   60.   60.  360.]
[ 248.  308.  368.  428.  